### ISSUE TITLE
Highlight cells with an unequal use of format specifiers.

### ISSUE THREAD

**Issue by Vogel612** [Vogel612/TranslationHelper#20]
To prevent runtime errors when translations become outdated and don't contain the correct format specifiers anymore it should be easy to find such mismatches between translations,

Highlight color would be Orange

**Comment by Vogel612** [comment]
Sounds like a Job for the Regex I wrote for Jeroen. We can read format specifiers out of Format strings with the following regex:

    "(?<!\{)\{(?:\{\{)*((?:\d+)(?::.*?)?)\}(?:\}\})*(?!\})"

**Comment by retailcoder** [comment]
:+1:  life saver
