### ISSUE TITLE
No feedback on save?

### ISSUE THREAD

**Issue by retailcoder** [Vogel612/TranslationHelper#38]
Clicking the "Save" button produces no feedback whatsoever: it's impossible to know if the save was successful without actually going and verifying the file.

Also the button has no feedback on hover *or* on click, so we don't actually know if *anything* happened.

**Comment by Vogel612** [comment]
I'll fix that. I assume a simple popup "Successfully saved changes" would be enough?  
Since I need to keep track of whether stuff has been saved one of these "Asterisk Markers" for modification would be in there, too...

**Comment by retailcoder** [comment]
yep. *any* kind of feedback would be welcome :+1:
