### ISSUE TITLE
Maximizing the dialog leaves a big gap in the middle

### ISSUE THREAD

**Issue by retailcoder** [Vogel612/TranslationHelper#40]
I would have expected the textboxes to stretch instead.

**Comment by Vogel612** [comment]
As would I. I assume you're talking about the "Choose your Resx files"-Dialog? or the actual Translation dialog?

**Comment by retailcoder** [comment]
I meant the actual translation dialog

**Comment by Vogel612** [comment]
Fixed this for JavaFX only. it was not an issue in the Swing UI. This means JavaFX now has a draggable delimiter between the two text-areas (which the swing UI doesn't have).
